### ISSUE TITLE
As a User I want to filter visitors by name, phone, email and address

### ISSUE THREAD

**Issue by sapozhnikovay** [iegorov/e-reception#12]
Introduce a client-side full-text filtering of visitors data by First name, Last name, Middle name, phone, email or address fields.

**Subtasks:**
- [x] Introduce search input above the table
- [x] Filter visitors dataset in a table case-insensitive by the data in Full name, Email, Phone & Address columns.
- [x] Allow user to clear the search input via the `Reset X` button. Button should be visible only when there is a value in the search field.
- [x] When there is no data found render text `No results.`

**Design mockups:**
https://www.figma.com/file/wiQu66c3xgh3WznbXA9jCU/E-Reception-mockups?type=design&node-id=223-14468&mode=design&t=gu5Fp6eXfZICLEn7-0

**Acceptance criteria:**
- User is able to filter visitors table data by First Name case-insensitive
- User is able to filter visitors table data by Last Name case-insensitive
- User is able to filter visitors table data by Middle Name case-insensitive
- User is able to filter visitors table data by Phone
- User is able to filter visitors table data by Email case-insensitive
- User is able to filter visitors table data by Address case-insensitive
- User is able to clear search field
- Clear search field button is present only when there is a value in the search field
- When search field has a value and no data has been found, User is able to see `No results.` text

**Linked issues:**
- is blocked by #7
