### ISSUE TITLE
As a User I want to sort the visitors table by Name and Birth date

### ISSUE THREAD

**Issue by sapozhnikovay** [iegorov/e-reception#31]
Allow User to sort by Name and Birth Date 

**Subtasks:**

- [ ] Introduce an ASC/DESC sort indicator button to the Name & Birth Date columns
- [ ] Add `Reset` item to the sort menu to reset the sort order

**Design mockups:**
https://www.figma.com/file/wiQu66c3xgh3WznbXA9jCU/E-Reception-mockups?type=design&node-id=223-13023&mode=design&t=e0ZQO5KMJTHtAPnN-0

**Acceptance criteria:**

- [ ] User is able to sort visitors data by Name or Birth Date columns in ASC or DESC order
- [ ] user is able to clear the sort order on a column

**Linked issues:**

is blocked by #7
