### ISSUE TITLE
As a User I want to open the Visitors page

### ISSUE THREAD

**Issue by sapozhnikovay** [iegorov/e-reception#6]
Implement `/visitors` page with basic layout, title & subtitle.

**Subtasks**:
- [x] Add a `layout.tsx` to be used for all pages. See https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts
- [x] Add a global layout header with 3 navigation links Appointments, Visitors, Settings. See example: https://github.com/shadcn-ui/ui/blob/main/apps/www/components/main-nav.tsx
- [x] Add a new page /visitors
- [x] Add Visitors page header with title and subtitle

**Design mockup**:
https://www.figma.com/file/wiQu66c3xgh3WznbXA9jCU/E-Reception-mockups?type=design&node-id=211%3A5112&mode=design&t=TF2rkxhfKdGBkSQ0-1

**Acceptance criteria**:
- User can open `Visitors` page via `/visitors` path in browser
- User can open `Visitors` page via `Visitors` link in global header
- User can see title and subtitle on `Visitors` page
