### ISSUE TITLE
As a User I want to view the visitors table

### ISSUE THREAD

**Issue by sapozhnikovay** [iegorov/e-reception#7]
Introduce visitors table on Visitors page.

**Subtasks:**
- [x] Implement a table component with 5 columns: `Name`, `Birth date`, `Email`, `Phone`, `Address`. See this guide for reference: https://ui.shadcn.com/docs/components/data-table#introduction
You may also find this implementation useful: https://github.com/shadcn-ui/ui/tree/main/apps/www/app/examples/tasks
- [x] Define a web app `Visitor` model with `zod`. See this file for example: https://github.com/shadcn-ui/ui/blob/main/apps/www/app/examples/tasks/data/schema.ts
I assume there will be fields like: `id`, `firstName`, `middleName`, `lastName`, `birthDate`, `email`, `phone`, `address`.
- [x] Provide some mock visitors data
- [x] Text `No data.` should be present if there is no data available for display.

**Design mockups:**
https://www.figma.com/file/wiQu66c3xgh3WznbXA9jCU/E-Reception-mockups?type=design&node-id=211%3A5112&mode=design&t=TF2rkxhfKdGBkSQ0-1
Empty view: https://www.figma.com/file/wiQu66c3xgh3WznbXA9jCU/E-Reception-mockups?type=design&node-id=223%3A14135&mode=design&t=TF2rkxhfKdGBkSQ0-1

**Acceptance criteria:**
- User is able to see a table with columns `Name`, `Birth date`, `Email`, `Phone`, `Address`
- When there is no data available text `No data.` is present.

**Linked issues:**
- is blocked by #6
