### ISSUE TITLE
As a User I want to see the visitors data from the database

### ISSUE THREAD

**Issue by sapozhnikovay** [iegorov/e-reception#8]
Introduce a solution to load data from PostgreSQL database into Visitors table

**Subtasks:**
- [ ] Introduce Prisma library. See this guide for reference: https://vercel.com/guides/nextjs-prisma-postgres
- [ ] Define Prisma model for Visitor
- [ ] Add `GET /api/visitors` endpoint to get the data from Postgres. See this guide for reference: https://nextjs.org/docs/app/building-your-application/routing/route-handlers
- [ ] Update table component to use the new data endpoint
- [ ] Seed some data to the database

**Acceptance criteria:**
- User is able to see all visitors' data from the database in the Visitors table

**Linked issues:**
- is blocked by #7
