### ISSUE TITLE
As a User I want to paginate data in the Visitors table

### ISSUE THREAD

**Issue by sapozhnikovay** [iegorov/e-reception#9]
Introduce a client-side solution to paginate data in the Visitors table

**Subtasks:**
- [x] Introduce pagination component under the table on the Visitors page.
- [x] Display only 10 items per page.
- [x] Allow user to change pages by clicking buttons.

**Design mockups:**
https://www.figma.com/file/wiQu66c3xgh3WznbXA9jCU/E-Reception-mockups?type=design&node-id=211%3A5112&mode=design&t=TF2rkxhfKdGBkSQ0-1

**Acceptance criteria:**
- User is able to see visitors table data by 10 on a page
- User is able to navigate to the next page
- User is able to navigate to the previous page
- User is able to navigate to the first page
- User is able to navigate to the last page
- First page button is disabled when user is on a first page
- Previous page button is disabled when user is on a first page
- Last page button is disabled when user is on a last page
- Next page button is disabled when user is on a last page

**Linked issues:**
- is blocked by #7
